[dev]
   command = "yarn dev"

[build]
  command = "yarn generate"
  publish = "dist"
  functions = "functions"

[functions]
  node_bundler = "esbuild"

# [[plugins]]
# package = "netlify-plugin-subfont"

# a redirect to fix the issue with netlify-cms
[[redirects]]
  from = "/admin#"
  to = "/admin/"

[[redirects]]
  from = "/admin#/"
  to = "/admin/"

[[redirects]]
  from = "/ramadan"
  to   = "/causes/25"

[[redirects]]
  from = "/ramadan"
  to   = "/causes/25"

[[redirects]]
  from = "/hospital"
  to   = "/causes/29"
  
[[redirects]]
  from = "/causes/hospital"
  to   = "/causes/29"

[[redirects]]
  from = "/school"
  to   = "/causes/28"
  
[[redirects]]
  from = "/causes/school"
  to   = "/causes/28"

[[redirects]]
  from = "/udhiya"
  to = "/causes/31"

[[redirects]]
  from = "/udhiyah"
  to = "/causes/31"

[[redirects]]
  from = "/causes/udhiya"
  to = "/causes/31"

[[redirects]]
  from = "/causes/udhiyah"
  to = "/causes/31"

[[plugins]]
package = "netlify-plugin-inline-functions-env"