[dev]
   command = "yarn dev"

[build]
  command = "yarn generate"
  publish = "dist"
  functions = "functions"

[functions]
  node_bundler = "esbuild"

# [[plugins]]
# package = "netlify-plugin-subfont"
