[dev]
   command = "yarn dev"

[build]
  command = "yarn generate"
  publish = "dist"
  functions = "functions"

[functions]
  node_bundler = "esbuild"

# [[plugins]]
# package = "netlify-plugin-subfont"

# a redirect to fix the issue with netlify-cms
[[redirects]]
  from = "/admin#"
  to = "/admin/"

[[redirects]]
  from = "/admin#/"
  to = "/admin/"

[[redirects]]
  from = "/ramadan"
  to   = "/causes/2"

[[redirects]]
  from = "/hospital"
  to   = "/causes/12"
  
[[redirects]]
  from = "/causes/hospital"
  to   = "/causes/12"

[[plugins]]
package = "netlify-plugin-inline-functions-env"