site_url: https://new.an-nadaa.com/
logo_url: https://new.an-nadaa.com/long-logo.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: develop
  repo: an-nadaaa/nda-front

media_folder: static/media
public_folder: /media

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  # en - English
  # ar - Arabic
  # ms - Malay
  # sw - Swahili
  locales: [en, ar, ms, sw]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - { label: Email Contact, name: contact, widget: string, hint: 'This email is used for the contact form' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
              hint: 'The default website language',
            }

  - label: 'Home Page Content'
    name: 'home'
    # Configure i18n for this collection.
    i18n:
      structure: single_file
      locales: [en, ar]
    files:
      - label: Hero Section
        name: hero
        file: 'content/site/home/hero_section.json'
        format: 'json'
        # Enable i18n for this file.
        i18n: true
        editor:
          preview: false
        fields:
          - {
              label: Video Location,
              name: location,
              widget: string,
              i18n: duplicate,
              default: '/media/video/What-Is-An-nadaa.mp4',
              hint: 'enter the name of the video or a url: YouTube, Vimeo',
            }
          - { label: 'Header', name: 'header', widget: 'string', i18n: true }
      - label: Story Section
        name: story
        i18n: true
        file: 'content/site/home/story.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - {
              label: Title,
              name: title,
              widget: string,
              default: 'An-Nadaa is bringing a huge positive impact for the underprivileged communities in Nigeria.',
              i18n: true,
            }
  - label: 'About Page Content'
    name: 'about'
    # Configure i18n for this collection.
    i18n:
      structure: single_file
      locales: [en, ar]
    files:
      - label: Statement section
        name: statement
        file: 'content/site/about/statement_section.json'
        format: 'json'
        # Enable i18n for this file.
        i18n: true
        editor:
          preview: false
        fields:
          - {
              label: Title,
              name: title,
              widget: string,
              i18n: duplicate,
              default: 'How it started',
              hint: 'Enter the title of statement',
            }
          - { label: 'Subtitle', name: 'subtitle', widget: 'string', i18n: duplicate, default:'A simple way to' }
          - { label: 'Goal', name: 'goal', widget: 'string', i18n: duplicate, default:'Lift others' }
          - { label: 'Description', name: 'description', widget: 'string', i18n: duplicate }
      - label: Story section
        name: story
        file: 'content/site/about/story_section.json'
        format: 'json'
        # Enable i18n for this file.
        i18n: true
        editor:
          preview: false
        fields:
          - { label: Title, name: title, widget: string, i18n: duplicate, default: 'Our story' }
          - { label: 'Subtitle', name: 'subtitle', widget: 'string', i18n: duplicate }
          - {
              label: 'First column Description',
              name: 'description1',
              widget: 'string',
              i18n: duplicate,
              hint:'Description added to the first column',
            }
          - {
              label: 'Second column Description',
              name: 'description2',
              widget: 'string',
              i18n: duplicate,
              hint:'Description added to the first column',
            }
      - label: Our values section
        name: value
        file: 'content/site/about/value_section.json'
        format: 'json'
        # Enable i18n for this file.
        i18n: true
        editor:
          preview: false
        fields:
          - { label: Title, name: title, widget: string, i18n: duplicate, default: 'Our values' }
          - { label: 'Subtitle', name: 'subtitle', widget: 'string', i18n: duplicate }
          - { label: 'Description', name: 'description', widget: 'string', i18n: duplicate }
      - label: Shaykh section
        name: shaykh
        file: 'content/site/about/shaykh_section.json'
        format: 'json'
        # Enable i18n for this file.
        i18n: true
        editor:
          preview: false
        fields:
          - {
              label: Image url,
              name: imageUrl,
              widget: markdown,
              i18n: duplicate,
              default: 'https://an-nadaa-media.s3.us-west-004.backblazeb2.com/website/photo_2022-03-17_13-50-53.jpg',
              hint: 'Enter the url of the image that will be added to Shayh section',
            }
          - {
              label: Title,
              name: title,
              widget: string,
              i18n: duplicate,
              default: 'Founder (Nigeria) & Deputy Chairman (Malaysia)',
            }
          - {
              label: 'Subtitle',
              name: 'subtitle',
              widget: 'string',
              i18n: duplicate,
              default: 'Meet Sheikh Ibrahim Nuhu',
            }
          - { label: 'Description', name: 'description', widget: 'string', i18n: duplicate }
      - label: Call to action section
        name: cta
        file: 'content/site/about/cta_section.json'
        format: 'json'
        # Enable i18n for this file.
        i18n: true
        editor:
          preview: false
        fields:
          - { label: Title, name: title, widget: string, i18n: duplicate, default: 'Starting changing lives Today.' }
          - {
              label: 'Subtitle',
              name: 'subtitle',
              widget: 'string',
              i18n: duplicate,
              default: 'We have many causes that are always open to contributions.',
            }
          - { label: 'button text', name: 'btnText', widget: 'string', i18n: duplicate, default: 'Explore more' }
          - { label: 'Button url', name: 'btnUrl', widget: 'string', i18n: duplicate, default: '/causes' }
      - label: Team section
        name: team
        file: 'content/site/about/team_section.json'
        format: 'json'
        # Enable i18n for this file.
        i18n: true
        editor:
          preview: false
        fields:
          - { label: Title, name: title, widget: string, i18n: duplicate, default: 'Our team' }
          - { label: 'Subtitle', name: 'subtitle', widget: 'string', i18n: duplicate }
  - label: 'Blogs'
    name: 'blog'
    label_singular: 'blog'
    folder: 'content/blog'
    create: true
    i18n: true
    format: 'frontmatter'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    # editor:
    #   preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true, i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false, i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  # FAQ collection
  - label: 'FAQ'
    name: 'faq'
    folder: 'content/faq'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    i18n: true
    fields:
      - { label: 'Question', name: 'question', widget: string, i18n: true, required: true }
      - { label: 'Answer', name: 'answer', widget: markdown, i18n: true, required: true }
  # Metrics Collection
  - label: 'Metrics'
    name: 'metrics'
    folder: 'content/metrics'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    i18n: true
    fields:
      - { label: 'Value', name: 'value', widget: 'number', value_type: 'int', required: true }
      - { label: 'Name', name: 'name', widget: 'string', i18n: true, required: true }
      - {
          label: 'Action',
          name: 'action',
          widget: 'string',
          i18n: true,
          default: 'Supported',
          required: true,
          hint: 'Can be Built, Supported or other action verbs',
        }
  # Testimonials Collection
  - label: 'Testimonials'
    name: 'testimonials'
    folder: 'content/testimonials'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    i18n: true
    fields:
      - { label: 'Testimony', name: 'testimony', widget: 'markdown', i18n: true, required: true }
      - { label: "Person's Name", name: 'name', widget: 'string', i18n: true, required: true }
      - { label: "Person's Title", name: 'title', widget: 'string', i18n: true, required: true }
      - {
          label: 'Locale',
          name: 'locale',
          widget: 'select',
          default: 'en',
          required: true,
          options: [en, ar, ms, sw],
          hint: 'Which locals this testimonial should be displayed on the home page',
        }
    # Team members collection
  - label: 'Team members'
    name: 'members'
    folder: 'content/members'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    i18n: true
    fields:
      - { label: 'Member image URL', name: 'imageUrl', widget: string, i18n: duplicate, required: true }
      - { label: 'Name', name: 'name', widget: string, i18n: duplicate, required: true }
      - { label: 'Role', name: 'role', widget: string, i18n: duplicate, required: true }
      - { label: 'Linkedin profile', name: 'linkedin', widget: string, i18n: duplicate, required: true }
      - { label: 'Twitter profile', name: 'twitter', widget: string, i18n: duplicate, required: true }
    # Values collection
  - label: 'Values'
    name: 'values'
    folder: 'content/values'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    i18n: true
    fields:
      - {
          label: 'Icon',
          name: 'icon',
          widget: string,
          i18n: duplicate,
          required: true,
          hint: 'You need to add the valid icon code from tabler-icons.io, example: LockAccessIcon for lock icon',
        }
      - { label: 'Title', name: 'title', widget: string, i18n: duplicate, required: true }
      - { label: 'Description', name: 'description', widget: string, i18n: duplicate, required: true }
